export const Specialty = [
  {value: 'acupuntura', name:'Acupuntura'},
  {value:'alergia', name:'Alergia e Imunologia'},  
  {value:'angiologia', name:'Angiologia'},
  {value:'angiorradiologia', name:'Angiorradiologia'},
  {value:'cancerologia', name:'Cancerologia'},
  {value:'cardiologia', name:'Cardiologia'},
  {value:'cardiologia_pediátrica', name:'Cardiologia Pediátrica'},
  {value:'cirurgia_cardiovascular', name:'Cirurgia Cardiovascular'},
  {value:'cirurgia_endovascular', name:'Cirurgia Endovascular'},
  {value:'cirurgia_geral', name:'Cirurgia Geral'},
  {value:'cirurgia_pediátrica', name:'Cirurgia Pediátrica'},
  {value:'cirurgia_plastica', name:'Cirurgia Plástica'},
  {value:'cirurgia_toracica', name:'Cirurgia Torácica'},
  {value:'cirurgia_vascular', name:'Cirurgia Vascular'},  
  {value:'cirurgia_trauma', name:'Cirurgia do Trauma'},
  {value:'citopatologia', name:'Citopatologia'},  
  {value:'coloproctologia', name:'Coloproctologia'},
  {value:'densitometria_ossea', name:'Densitometria Óssea'},
  {value:'dermatologia', name:'Dermatologia'},
  {value:'ecocardiografia', name:'Ecocardiografia'},
  {value:'endoscopia', name:'Endoscopia'},
  {value:'endoscopia Digestiva', name:'Endoscopia Digestiva'},
  {value:'endoscopia Ginecológica', name:'Endoscopia Ginecológica'},
  {value:'endoscopia Respiratória', name:'Endoscopia Respiratória'},
  {value:'ergometria', name:'Ergometria'},
  {value:'foniatria', name:'Foniatria'},
  {value:'gastroenterologia', name:'Gastroenterologia'},
  {value:'genética Médica', name:'Genética Médica'},
  {value:'geriatria', name:'Geriatria'},
  {value:'hinecologia', name:'Ginecologia'},
  {value:'hansenologia', name:'Hansenologia'},
  {value:'hematologia', name:'Hematologia'},
  {value:'hematologia', name:'Hematologia'},
  {value:'hemodinâmica', name:'Hemodinâmica'},
  {value:'hemoterapia', name:'Hemoterapia'},
  {value:'hemoterapia Pediátrica', name:'Hemoterapia Pediátrica'},
  {value:'hepatologia', name:'Hepatologia'},
  {value:'homeopatia', name:'Homeopatia'},
  {value:'imunologia Pediátrica', name:'Imunologia Pediátrica'},
  {value:'infectologia', name:'Infectologia'},
  {value:'infectologia Hospitalar', name:'Infectologia Hospitalar'},
  {value:'infectologia Pediátrica', name:'Infectologia Pediátrica'},
  {value:'mamografia', name:'Mamografia'},
  {value:'mastologia', name:'Mastologia'},
  {value:'medicina_fetal', name:'Medicina Fetal'},
  {value:'medicina_paliativa', name:'Medicina Paliativa'},
  {value:'medicina_tropical', name:'Medicina Tropical'},    
  {value:'medicina_sono', name:'Medicina do Sono'},
  {value:'nefrologia', name:'Nefrologia'},
  {value:'nefrologia_pediátrica', name:'Nefrologia Pediátrica'},
  {value:'neonatologia', name:'Neonatologia'},
  {value:'neurocirurgia', name:'Neurocirurgia'},
  {value:'neurofisiologia_clínica', name:'Neurofisiologia Clínica'},
  {value:'neurologia', name:'Neurologia'},
  {value:'neurologia_pediátrica', name:'Neurologia Pediátrica'},
  {value:'neurorradiologia', name:'Neurorradiologia'},
  {value:'nutrologia', name:'Nutrologia'},
  {value:'nutrologia_pediátrica', name:'Nutrologia Pediátrica'},
  {value:'obstetrícia', name:'Obstetrícia'},
  {value:'oftalmologia', name:'Oftalmologia'},
  {value:'ortopedia_traumatologia', name:'Ortopedia e Traumatologia'},
  {value:'otorrinolaringologia', name:'Otorrinolaringologia'},
  {value:'patologia', name:'Patologia'},
  {value:'patologia_clínica', name:'Patologia Clínica'},
  {value:'pediatria', name:'Pediatria'},
  {value:'pneumologia', name:'Pneumologia'},
  {value:'pneumologia_pediátrica', name:'Pneumologia Pediátrica'},
  {value:'psicogeriatria', name:'Psicogeriatria'},
  {value:'psicoterapia', name:'Psicoterapia'},
  {value:'psiquiatria', name:'Psiquiatria'},
  {value:'psiquiatria_forense', name:'Psiquiatria Forense'},
  {value:'radiologia', name:'Radiologia'},
  {value:'radioterapia', name:'Radioterapia'},
  {value:'reumatologia', name:'Reumatologia'},
  {value:'reumatologia_pediátrica', name:'Reumatologia Pediátrica'},
  {value:'sexologia', name:'Sexologia'},
  {value:'ultrassonografia', name:'Ultrassonografia'},
  {value:'urologia', name:'Urologia'},
];

export const Price = [100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 750, 800, 850, 900,950, 1000, 1050];